### ISSUE TITLE
Data Update

### ISSUE THREAD

**Issue by ihapoorv** [Perishleaf/data-visualisation-scripts#6]
Please update the data. I'm learning data visualization from your data only. So please update time to time. Thank You.

**Comment by Perishleaf** [comment]
Hey Ihapoorv,

I am recently focusing on COVID-19 dashboard development. The data inside that sub-folder update daily if that is what you are asking for.

Regarding other visualisations, I may not be able to update them regularly at this stage.

Thanks for your support!

Jun
